# Generated by Django 5.0.6 on 2024-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon_url',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
