# Generated by Django 5.0.6 on 2024-07-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_icon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='repeat_frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='repeat_interval',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='unit',
        ),
        migrations.AddField(
            model_name='habit',
            name='days_of_month',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='times_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
