# Generated by Django 5.0.6 on 2024-08-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_remove_habit_location_remove_habit_repeat_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='dates_completed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
